version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "demo-ml"
        Alias: "myLambdaFunctionAlias"
        ImageUri: <IMAGE_URI_FROM_BUILD>
